//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRent.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public int ClientEquipmentID { get; set; }
        public System.DateTime RentStart { get; set; }
        public System.DateTime RentEnd { get; set; }
        public System.DateTime ReturnTime { get; set; }
    
        public virtual ClientEquipment ClientEquipment { get; set; }
    }
}
